-- mPanel 009: privacy-conscious first-party analytics
create table if not exists public.site_analytics_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  site_id uuid not null unique references public.sites(id) on delete cascade,
  public_key text not null unique,
  enabled boolean not null default true,
  track_page_views boolean not null default true,
  track_referrers boolean not null default true,
  retention_days integer not null default 90 check (retention_days between 7 and 730),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  site_id uuid not null references public.sites(id) on delete cascade,
  event_type text not null default 'page_view' check (event_type in ('page_view','custom')),
  path text not null default '/',
  referrer text,
  session_id text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists idx_analytics_events_site_created on public.analytics_events(site_id,created_at desc);
create index if not exists idx_analytics_events_site_path on public.analytics_events(site_id,path);
create index if not exists idx_analytics_events_site_session on public.analytics_events(site_id,session_id);
alter table public.site_analytics_settings enable row level security;
alter table public.analytics_events enable row level security;
drop policy if exists site_analytics_settings_owner_all on public.site_analytics_settings;
create policy site_analytics_settings_owner_all on public.site_analytics_settings for all using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists analytics_events_owner_select on public.analytics_events;
create policy analytics_events_owner_select on public.analytics_events for select using(exists(select 1 from public.sites s where s.id=analytics_events.site_id and s.user_id=auth.uid()));
create or replace function public.set_analytics_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists site_analytics_settings_updated_at on public.site_analytics_settings;
create trigger site_analytics_settings_updated_at before update on public.site_analytics_settings for each row execute function public.set_analytics_updated_at();
create or replace function public.lock_analytics_owner() returns trigger language plpgsql as $$ begin new.user_id=old.user_id; new.site_id=old.site_id; new.public_key=old.public_key; return new; end $$;
drop trigger if exists lock_site_analytics_owner on public.site_analytics_settings;
create trigger lock_site_analytics_owner before update on public.site_analytics_settings for each row execute function public.lock_analytics_owner();
create or replace function public.seed_analytics_settings() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.site_analytics_settings(user_id,site_id,public_key) values(new.user_id,new.id,encode(gen_random_bytes(18),'hex')) on conflict(site_id) do nothing; return new; end $$;
drop trigger if exists seed_analytics_after_site on public.sites;
create trigger seed_analytics_after_site after insert on public.sites for each row execute function public.seed_analytics_settings();
insert into public.site_analytics_settings(user_id,site_id,public_key) select s.user_id,s.id,encode(gen_random_bytes(18),'hex') from public.sites s on conflict(site_id) do nothing;
create or replace function public.record_analytics_event(p_public_key text,p_path text default '/',p_referrer text default null,p_session_id text default null,p_user_agent text default null,p_event_type text default 'page_view') returns boolean language plpgsql security definer set search_path=public as $$
declare target_site uuid;
begin
 if length(coalesce(p_public_key,''))<16 then return false; end if;
 if p_event_type not in ('page_view','custom') then return false; end if;
 select site_id into target_site from public.site_analytics_settings where public_key=p_public_key and enabled=true;
 if target_site is null then return false; end if;
 insert into public.analytics_events(site_id,event_type,path,referrer,session_id,user_agent) values(target_site,p_event_type,left(coalesce(p_path,'/'),500),left(nullif(p_referrer,''),1000),left(nullif(p_session_id,''),128),left(nullif(p_user_agent,''),1000));
 return true;
end $$;
revoke all on function public.record_analytics_event(text,text,text,text,text,text) from public;
grant execute on function public.record_analytics_event(text,text,text,text,text,text) to anon,authenticated;
insert into public.system_checks(user_id,site_id,check_key,status,message) select s.user_id,s.id,'analytics','pending','Analytics not checked yet' from public.sites s on conflict(site_id,check_key) do nothing;
